const HomeScreen = './homeScreen/';

export default {
  /** home screen */
  india: require(`${HomeScreen}india.png`),
  location_icon: require(`${HomeScreen}location_icon.png`),
  beard: require(`${HomeScreen}beard.png`),
  beard_light: require(`${HomeScreen}beard_light.png`),
  spa: require(`${HomeScreen}spa.png`),
  spa_light: require(`${HomeScreen}spa_light.png`),
  hair: require(`${HomeScreen}hair.png`),
  nail: require(`${HomeScreen}nail.png`),
  nail_light: require(`${HomeScreen}nail_light.png`),
  offer_card: require(`${HomeScreen}offer_card.png`),
  salon_image: require(`${HomeScreen}salon_image.png`),
  offer_icon: require(`${HomeScreen}offer_Icon.png`),
  favorite_icon: require(`${HomeScreen}favoritee.png`),
  heart: require(`${HomeScreen}heart.png`),
  artist: require(`${HomeScreen}artist.png`),
  artist2: require(`${HomeScreen}artist2.png`),
  equalizer: require(`${HomeScreen}equalizer.png`),
  category: require(`${HomeScreen}category.png`),
  productTransparent1: require(`${HomeScreen}product1transparent.png`),
  productTransparent2: require(`${HomeScreen}product2transparent.png`),
  productcard1: require(`${HomeScreen}productcard1.png`),
  productcard2: require(`${HomeScreen}productcard2.png`),
  productcard1hd: require(`${HomeScreen}product1hd.png`),
  productcard2hd: require(`${HomeScreen}product2hd.png`),
  deal: require(`${HomeScreen}deal.png`),
  coupon: require(`${HomeScreen}coupon.png`),
  salon: require(`${HomeScreen}salon.jpg`),
  dryer: require(`${HomeScreen}dryer.png`),
  comb: require(`${HomeScreen}comb.png`),
  attitude: require(`${HomeScreen}Attitude.png`),
  conversation: require(`${HomeScreen}Conversation.png`),
  outstanding: require(`${HomeScreen}Outstanding.png`),
  square: require(`${HomeScreen}square.png`),
  shopping_cart: require(`${HomeScreen}shopping-cart.png`),
  productImageSquare1: require(`${HomeScreen}productimagesquare.png`),
  productImageSquare2: require(`${HomeScreen}productimagesquare2.png`),
  bucketO: require(`${HomeScreen}bucketOrange.png`),
  shieldnew: require(`${HomeScreen}shieldnew.png`),
  seat: require(`${HomeScreen}seat.png`),
  mask: require(`${HomeScreen}mask.png`),
  safe2: require(`${HomeScreen}safe.png`),
  map: require(`${HomeScreen}map.png`),
  chair: require(`${HomeScreen}chair.png`),
  best: require(`${HomeScreen}best_dark.png`),
  best_light: require(`${HomeScreen}best.png`),
  neame: require(`${HomeScreen}neame_dark.png`),
  neame_light: require(`${HomeScreen}neame.png`),
  saftey: require(`${HomeScreen}saftey_dark.png`),
  saftey_light: require(`${HomeScreen}saftey.png`),
  shield: require(`${HomeScreen}shield_dark.png`),
  shield_light: require(`${HomeScreen}shield.png`),
  makup: require(`${HomeScreen}makup_dark.png`),
  makup_light: require(`${HomeScreen}makup.png`),
  square2: require(`${HomeScreen}square2.png`),
  square3: require(`${HomeScreen}square3.png`),
  star: require(`${HomeScreen}star.png`),

  thumbsUp: require(`${HomeScreen}thumbs-up.png`),

  barberPoll: require(`${HomeScreen}barberpoll.png`),
  serviceIcon: require(`${HomeScreen}serviceIcon.png`),
  productColor: require(`${HomeScreen}productColor.png`),
  discountColor: require(`${HomeScreen}discountColor.png`),

  exit: require(`${HomeScreen}exit.png`),
  lifeSaver: require(`${HomeScreen}life-saver.png`),
  discount: require(`${HomeScreen}discount.png`),
  creditCard: require(`${HomeScreen}credit-card.png`),
  receipt: require(`${HomeScreen}receipt.png`),
};
