import { Dimensions, StyleSheet } from 'react-native';
import { colors, fonts } from '../../constants/styles';
import { scale } from '../../utils/scale';


const {width} = Dimensions.get('window');

export default StyleSheet.create({
  container2: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: scale(10),
    paddingVertical: scale(5),
    // marginBottom: scale(10),
    shadowOpacity: 0.3,
    shadowRadius: 5,
    shadowOffset: {
      height: 0,
      width: 0,
    },
    //android
    elevation: 1,
    // ...ifIphoneX(
    //   {
    //     // marginTop: scale(10),
    //   },
    //   {
    //     // marginTop: scale(15),
    //   },
    // ),
  },
  container: {
    flexGrow: 1,
    backgroundColor: '#212121',
  },
  headerContentContainerStyle: {
    marginTop: scale(5),
    paddingRight: scale(20),
    marginLeft: scale(10),
  },
  offerCard: {
    height: scale(200),
    width: scale(256),
    // marginHorizontal:(5),
    resizeMode: 'contain',
  },
  offerCardTop: {
    height: scale(200),
    width: scale(256),
    // marginHorizontal:(5),
    resizeMode: 'contain',
  },
  categotyContentContainerStyle: {
    paddingRight: scale(20),
    marginTop: scale(23),
  },
  renderCategoryItemContainer: {
    marginLeft: scale(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryIcon: {
    height: scale(64),
    width: scale(64),
    resizeMode: 'contain',
  },
  categoryTitle: {
    color: '#fff',
    fontSize: scale(12),
    lineHeight: scale(21),
    fontFamily: fonts.avenirNextRegular,
  },
  topStlist: {
    marginTop: scale(30),
    marginBottom: scale(20),
    color: '#fff',
    fontSize: scale(16),
    lineHeight: scale(21),
    marginLeft: scale(17),
    fontFamily: fonts.helveticaNeueMedium,
  },
  topStylistContainerStyle: {
    paddingLeft: scale(17),
  },
  nearBySalons: {
    // marginTop: scale(30),
    // marginBottom: scale(20),
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'space-between',
    // marginHorizontal: scale(17),
  },
  nearBy: {
    fontSize: scale(16),
    lineHeight: scale(21),
    color: '#fff',
    fontFamily: fonts.helveticaNeueMedium,
  },
  equalizer: {
    height: scale(19),
    width: scale(19),
    resizeMode: 'contain',
  },
  nearBySalonsContainer: {
    marginHorizontal: scale(17),
  },
  featuredContainer: {
    marginLeft: scale(17),
    marginRight: scale(1),
  },
  couponOffer: {
    height: scale(220),
    width: scale(350),
    marginHorizontal: scale(10),
    marginTop: scale(30),
    resizeMode: 'contain',
  },
  scrollViewContainer: {
    width: scale(134),
    backgroundColor: 'rgba(0,0,0,0.3)',
    marginLeft: scale(-30),
    // marginBottom:scale(25)
  },
  titleOne: {
    fontSize: scale(14),
    fontWeight: 'bold',
    color: colors.grayColor,
    textAlign: 'center',
    padding: scale(20),
    fontFamily: fonts.avenirNextMedium,
  },
  activeStyle: {
    width: scale(5),
    backgroundColor: colors.darkOrange,
    position: 'absolute',
    bottom: scale(15),
    top: scale(15),
    right: 0,
  },
  menuContainer: {
    flexDirection: 'row',
  },
  menuText: {
    fontSize: scale(16),
    width: '90%',
    fontFamily: fonts.avenirNextDemiBold,
  },
  sortMainContainer: {
    flexDirection: 'row',
    marginVertical: scale(10),
  },
  filterOptionContainer: {
    width: '60%',
    marginHorizontal: scale(10),
    marginVertical: scale(10),
    padding: scale(15),
  },
  radioButtonWraper: {
    marginHorizontal: scale(10),
    marginVertical: scale(5),
  },
  radioButtonLable: {
    fontSize: scale(14),
    marginHorizontal: scale(20),
    marginVertical: scale(10),
    fontFamily: fonts.avenirNextMedium,
  },
  filterMenuButtonContainer: {
    flexDirection: 'row',
  },
  customApplyButton: {
    marginHorizontal: scale(5),
    width: scale(203),
    height: scale(52),
    alignItems: 'center',
    marginLeft: scale(20),
  },
  customSubmitButton: {
    marginHorizontal: scale(5),
    width: scale(344),
    height: scale(52),
    alignItems: 'center',
    marginVertical: scale(15),
  },
  clearButton: {
    width: scale(96),
    height: scale(52),
    borderRadius: scale(11),
    justifyContent: 'center',
    marginLeft: scale(5),
  },
  clearButtonText: {
    fontSize: scale(14),
    textAlign: 'center',
    fontFamily: fonts.robotoRegular,
  },
  filterContentContainerStyle: {
    marginHorizontal: scale(10),
    marginVertical: scale(10),
  },
  filterBackground: {
    borderColor: colors.grayColor,
    marginHorizontal: scale(10),
    flexDirection: 'row',
    padding: scale(10),
    borderRadius: scale(6),
    paddingHorizontal: scale(20),
    // shadowColor: "#000",
    // shadowOffset: {
    //   width: 0,
    //   height: 4,
    // },
    // shadowOpacity: 0.30,
    // shadowRadius: 4.65,
    // elevation: 8,
  },
  filterIcon: {
    backgroundColor: colors.darkOrange,
    marginLeft: scale(10),
    borderRadius: scale(3),
  },
  filterCountText: {
    fontSize: scale(13),
    fontFamily: fonts.helveticaNeueMedium,
  },
  customViewMoreButton: {
    width: '80%',
    marginHorizontal: scale(35),
    marginVertical: scale(30),
  },
  footerComponent: {
    flexDirection: 'row',
    // alignContent: 'center',
    // justifyContent: 'center',
  },
  liveText: {
    fontSize: scale(50),
    fontFamily: fonts.helveticaNeueCondensedBold,
    letterSpacing: scale(3.8),
    color: '#696969',
    marginLeft: scale(20),
    fontWeight: 'bold',
  },
  dryerStyle: {bottom: scale(1)},
  madeByText: {
    marginLeft: scale(20),
    fontSize: scale(12),
    fontFamily: fonts.helveticaNeueLight,
    color: '#9B9B9B',
    marginTop: scale(20),
  },
  viewAll: {
    fontFamily: fonts.helveticaNeueRegular,
    fontSize: scale(14),
    color: colors.grayBorder,
  },
  leftMargin: {marginLeft: scale(10)},
  exclusiveText: {
    fontFamily: fonts.helveticaNeueLight,
    fontSize: scale(14),
    color: colors.orangeBorder,
    marginVertical: scale(2),
  },
  spendText: {
    fontFamily: fonts.helveticaNeueLight,
    fontSize: scale(16),
    marginVertical: scale(2),
  },
  voucherText: {
    fontFamily: fonts.helveticaNeueLight,
    fontSize: scale(14),
    marginVertical: scale(2),
  },
  worthText: {
    fontFamily: fonts.helveticaNeueLight,
    fontSize: scale(14),
    marginVertical: scale(2),
  },
  offerForYouContainer: {
    width: '60%',
    marginTop: scale(20),
    marginBottom: scale(40),
    elevation: 1,
    borderTopWidth: 0.3,
    borderBottomWidth: 0.3,
    borderColor: '#DFDFDF',
  },
  secondaryComponent: {
    marginHorizontal: scale(10),
    marginVertical: scale(20),
  },
  lastComponent: {
    marginTop: scale(30),
    marginBottom: scale(300),
  },
  welcomeText: {
    fontFamily: fonts.helveticaNeueLight,
    fontSize: scale(14),
    color: colors.textGrey,
    marginLeft: scale(17),
  },
  salonNameText: {
    fontFamily: fonts.helveticaNeueMedium,
    fontSize: scale(26),
    marginLeft: scale(17),
  },
  horizontalLine: {
    height: 1,
    // width: scale(210),
    backgroundColor: colors.greyHomeBorder,
    marginHorizontal: scale(16),
    marginTop: scale(2),
    marginBottom: scale(8),
  },
  slotText: {
    fontSize: scale(14),
    fontFamily: fonts.helveticaNeueLight,
    color: colors.teal,
    marginHorizontal: scale(17),
  },

  smallButton: {
    // backgroundColor: 'rgba(249,213,183,0.3)',
    backgroundColor: '#F9D5B7',
    borderColor: colors.orangeText,
    borderRadius: scale(20),
    borderWidth: scale(2),
    height: scale(32),
    width: scale(112),
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: scale(16),
    // padding: scale(10),
  },
  firstInfo: {
    marginHorizontal: scale(10),
    borderRadius: scale(16),
    height: scale(89),
    width: scale(111),
    marginTop: scale(16),
  },
  flexRow: {
    flexDirection: 'row',
    marginVertical: scale(5),
    // marginLeft: scale(8),
    marginHorizontal: scale(20),
  },
  flexRow4: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  firstOfferTextTitle: {
    fontSize: scale(14),
    fontFamily: fonts.helveticaNeueMedium,
  },
  firstOfferTextTitle2: {
    fontSize: scale(12),
    fontFamily: fonts.helveticaNeueLight,
    color: colors.grayBorder,
    width: '40%',
    marginTop: scale(5),
  },
  firstOfferTextTitle3: {
    fontSize: scale(12),
    fontFamily: fonts.helveticaNeueLight,
    color: colors.textGrey,
    marginTop: scale(10),
    marginLeft: scale(5),
  },
  safeText: {
    fontSize: scale(12),
    fontFamily: fonts.helveticaNeueMedium,
    marginLeft: scale(5),
  },
  firstComponent: {
    borderWidth: scale(2),
    borderColor: colors.orangeText,
    marginHorizontal: scale(10),
    borderRadius: scale(16),
    // padding: scale(10),
    // backgroundColor: 'rgba(249,213,183,0.3)',

    backgroundColor: '#F9D5B7',

    height: scale(89),
    width: scale(170),
    marginTop: scale(16),
  },
  offerCardTop1: {
    height: scale(30),
    width: scale(30),
    resizeMode: 'contain',
    position: 'absolute',
    right: scale(20),
    top: scale(-5),
  },
  offerCardTop2: {
    height: scale(90),
    width: scale(70),
    resizeMode: 'contain',
    position: 'absolute',
    right: scale(-27),
    top: scale(-5),
  },
  couponShieldImage: {
    height: scale(120),
    width: scale(120),
    resizeMode: 'contain',
    position: 'absolute',
    right: scale(-20),
    top: scale(-20),
  },
  couponShield: {
    marginHorizontal: scale(17),
    borderRadius: scale(8),
    // paddingHorizontal: scale(10),
    marginTop: scale(20),
    height: scale(104),
    width: scale(342),
    justifyContent: 'center',
  },
  couponShieldTextTitle: {
    fontSize: scale(16),
    fontFamily: fonts.helveticaNeueMedium,
    width: '70%',
    color: colors.White,
  },
  couponShieldTextTitle2: {
    fontSize: scale(13),
    fontFamily: fonts.helveticaNeueLight,
    width: '70%',
    marginVertical: scale(5),
    color: colors.White,
  },
  couponShieldTextTitle3: {
    fontSize: scale(12),
    fontFamily: fonts.helveticaNeueMedium,
    color: colors.White,
    // width: '70%',
  },
  arrowRight: {
    marginHorizontal: scale(5),
  },
  ratingText: {
    fontSize: scale(14),
    fontFamily: fonts.robotoRegular,
    marginLeft: scale(20),
    textAlign: 'right',
  },
  flexDirection: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: scale(17),
  },
  flexR: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginHorizontal: scale(17),
  },
  ratingContainer: {
    flexDirection: 'row',
    backgroundColor: colors.teal,
    borderRadius: scale(5),
    height: scale(24),
    width: scale(55),
    justifyContent: 'center',
    alignItems: 'center',
  },
  ratingIcon: {
    height: scale(15),
    width: scale(15),
    resizeMode: 'contain',
    alignSelf: 'center',
    tintColor: colors.white,
  },
  ratingTitle: {
    fontSize: scale(12),
    lineHeight: scale(21),
    color: colors.White,
    fontFamily: fonts.avenirNextRegular,
    marginLeft: scale(5),
  },
  shieldScoreText: {
    fontSize: scale(12),
    color: colors.orangeText,
    fontFamily: fonts.helveticaNeueMedium,
  },
  styleImageView: {
    height: scale(48),
    width: scale(56),
    borderRadius: scale(12),
  },
  reviewPanelContain: {
    marginHorizontal: scale(12),
    marginBottom: scale(200),
  },
  salonNameReview: {
    fontSize: scale(16),
    fontFamily: fonts.helveticaNeueMedium,
  },
  salonLocationReview: {
    fontSize: scale(14),
    color: colors.textGrey,
    fontFamily: fonts.helveticaNeueLight,
  },
  marginLeft: {
    marginLeft: scale(16),
    marginRight: scale(5),
  },
  rateText: {
    fontSize: scale(14),
    fontFamily: fonts.helveticaNeueMedium,
    marginTop: scale(16),
    marginBottom: scale(8),
  },
  ratingBox: {
    height: scale(33),
    width: scale(57),
    borderRadius: scale(8),
    backgroundColor: colors.greyHomeBorder,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginRight: scale(8),
    // padding: scale(10),
    // paddingHorizontal: scale(15),
  },
  ambienceButton: {
    height: scale(32),
    width: scale(70),
    borderRadius: scale(8),
    borderWidth: scale(1),
    borderColor: colors.greyHomeBorder,
    // backgroundColor: colors.greyHomeBorder,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginRight: scale(8),
    marginBottom: scale(8),
  },
  ambienceText: {
    fontSize: scale(12),
    fontFamily: fonts.helveticaNeueThin,
  },
  indexNumber: {
    fontSize: scale(16),
    fontFamily: fonts.helveticaNeueThin,
  },
  starLogo: {
    height: scale(14),
    width: scale(14),
    marginLeft: scale(5),
  },
  flexBox: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  rateName: {
    fontSize: scale(14),
    fontFamily: fonts.helveticaNeueMedium,
    color: colors.green,
  },
  subHeading: {
    fontSize: scale(12),
    fontFamily: fonts.helveticaNeueLight,
    color: colors.grayColor,
    marginTop: scale(4),
  },
  bottomLine: {
    borderBottomWidth: scale(1),
    borderColor: colors.greyHomeBorder,
    marginTop: scale(4),
    marginBottom: scale(8),
  },
});
