import {StyleSheet, Platform, PixelRatio} from 'react-native';
import {scale, screenHeight, fontScale} from '../../utils/scale';
import {colors, fonts, SCREENWIDTH} from '../../constants/styles';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.screenBackground,
    ...Platform.select({
      android: {
        marginTop: scale(30),
      },
    }),
  },

  scrollContainer: {
    // flex: 1,
    // marginTop:scale(20),
    // marginBottom:scale(20),
  },
  backButton: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(9),
    left: scale(10),
    top: scale(20),
    position: 'absolute',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  galleryButton: {
    width: scale(140),
    height: scale(35),
    padding: scale(8),
    borderRadius: scale(9),
    right: scale(10),
    top: scale(250),
    position: 'absolute',
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
  },
  imageContainer: {
    width: SCREENWIDTH,
    height: scale(250),
  },
  detailContainer: {
    flexDirection: 'row',
    marginHorizontal: scale(20),
    marginVertical: scale(10),
  },
  detailText1: {
    width: '80%',
  },
  detailText2: {
    // width: '90%',
    alignSelf: 'flex-start',
    paddingVertical: scale(5),
    marginHorizontal: scale(10),
    borderRadius: scale(10),
    // paddingHorizontal: scale(5),
  },
  galleryText: {
    color: colors.white,
    alignItems: 'center',
    fontFamily: fonts.avenirNextMedium,
    fontSize: scale(14),
  },
  viewCart: {
    textAlign: 'center',
    marginTop: scale(5),
    fontFamily: fonts.helveticaNeueMedium,
    fontSize: scale(13),
  },
  openText: {
    color: colors.orangeText,
    // marginTop: scale(5),
    fontFamily: fonts.helveticaNeueMedium,
    fontSize: scale(12),
  },
  timeText: {
    fontSize: scale(10),
    fontFamily: fonts.helveticaNeueRegular,
    color: '#9B9B9B',
    marginHorizontal: scale(10),
    alignSelf: 'center',
    marginTop: scale(10),
  },
  salonName: {
    // fontSize: scale(24),
    fontFamily: fonts.helveticaNeueMedium,
    fontSize: 18 / PixelRatio.getFontScale(),
  },
  locationText: {
    fontSize: scale(12),
    fontFamily: fonts.helveticaNeueLight,
    color: '#696969',
  },
  ratingText: {
    fontSize: scale(14),
    fontFamily: fonts.robotoRegular,
    marginLeft: scale(15),
  },
  reviewText: {
    fontSize: scale(12),
    fontFamily: fonts.avenirNextRegular,
  },
  flexDirection: {
    flexDirection: 'row',
  },
  topStlist: {
    marginTop: scale(30),
    color: '#fff',
    fontSize: scale(16),
    lineHeight: scale(21),
    marginLeft: scale(17),
    fontFamily: fonts.helveticaNeueMedium,
  },
  viewAll: {
    marginTop: scale(10),
    color: colors.grayColor,
    fontSize: scale(14),
    lineHeight: scale(21),
    marginLeft: scale(20),
    fontFamily: fonts.helveticaNeueMedium,
  },
  topStylistContainerStyle: {
    paddingLeft: scale(17),
  },
  servicesText: {
    fontSize: scale(16),
    fontFamily: fonts.robotoRegular,
    marginTop: scale(30),
    lineHeight: scale(21),
    marginLeft: scale(17),
    marginBottom: scale(20),
  },
  amenitiesText: {
    fontSize: scale(18),
    fontFamily: fonts.avenirNextMedium,
    marginTop: scale(10),
    lineHeight: scale(21),
    marginLeft: scale(17),
    marginBottom: scale(10),
  },
  amenitiesMainContainer: {
    marginHorizontal: scale(20),
    marginVertical: scale(15),
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'space-between',
    // backgroundColor: 'red',
    width: '40%',
  },
  centerText: {
    // alignSelf: 'center',
    marginLeft: scale(10),
    // justifyContent: 'center',
  },
  amenitiesSub: {
    width: scale(30),
    height: scale(30),
    resizeMode: 'contain',
  },
  drinkText: {
    fontSize: scale(12),
    fontFamily: fonts.helveticaNeueLight,
    marginLeft: scale(10),
    marginRight: scale(5),
  },
  drinkContainer: {
    flexDirection: 'row',
    // marginHorizontal:scale(50),
    marginVertical: scale(5),
    marginLeft: scale(45),
  },
  flexStyle: {
    flex: 1,
  },
  amenitiesMain: {
    marginTop: scale(30),
    marginBottom: scale(5),
    // borderTopWidth: scale(1),
    // borderBottomWidth: scale(1),
    // borderColor: colors.greyHomeBorder,
  },
  cartButton: {
    marginHorizontal: scale(15),
    width: '90%',
    borderRadius: scale(10),
  },
  timeContainer: {
    width: '15%',
    paddingVertical: scale(10),
  },
  timeSubContainer: {
    width: '52%',
    marginHorizontal: scale(5),
  },
  weekNameText: {
    fontSize: scale(14),
    textAlign: 'center',
  },
  weekDateText: {
    marginTop: scale(10),
    textAlign: 'center',
  },
  timeNameContainer: {
    flexDirection: 'row',
    marginVertical: scale(10),
    flexWrap: 'wrap',
  },
  timeSelectContainer: {
    paddingHorizontal: scale(20),
    paddingVertical: scale(10),
    flexDirection: 'row',
    marginHorizontal: scale(5),
    borderRadius: scale(5),
    marginVertical: scale(5),
  },
  mainTimePicker: {
    marginLeft: scale(20),
  },
  preferedTimeText: {
    fontSize: scale(16),
    marginVertical: scale(20),
    fontFamily: fonts.avenirNextMedium,
  },
  selectedDataText: {
    fontSize: scale(18),
    marginTop: scale(15),
    marginBottom: scale(10),
    fontWeight: 'bold',
  },
  offerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: scale(5),
  },
  offerIcon: {
    height: scale(16),
    width: scale(16),
    resizeMode: 'contain',
    marginRight: scale(5),
  },
  offerTitle: {
    fontSize: scale(12),
    lineHeight: scale(21),
    color: '#fff',
    fontFamily: fonts.avenirNextRegular,
  },
  pickerStyle: {
    height: scale(45),
    width: scale(120),
    color: '#FFF',
    fontFamily: fonts.helveticaNeueMedium,
    fontSize: scale(16),
  },
  dropdownIcon: {
    position: 'absolute',
    left: scale(-50),
    justifyContent: 'center',
    marginVertical: scale(Platform.OS === 'ios' ? 0 : 15),
    marginLeft: scale(Platform.OS === 'ios' ? 5 : 10),
  },
  pickerContainer: {
    width: '30%',
    justifyContent: 'center',
    marginLeft: scale(-10),
  },
  madeByText: {
    marginLeft: scale(20),
    fontSize: scale(12),
    fontFamily: fonts.helveticaNeueLight,
    color: '#9B9B9B',
    // marginVertical: scale(20),
    paddingBottom: scale(100),
  },
  offerCard: {
    height: scale(180),
    width: scale(200),
    marginHorizontal: 5,
    resizeMode: 'contain',
  },
  serviceName: {
    fontSize: scale(18),
    lineHeight: scale(18),
    fontFamily: fonts.helveticaNeueMedium,
  },
  serviceDetail: {
    fontSize: scale(12),
    lineHeight: scale(15),
    color: colors.grayBorder,
    fontFamily: fonts.helveticaNeueLight,
    letterSpacing: 1,
  },
  serviceDataContainer: {
    marginTop: scale(20),
    borderTopLeftRadius: scale(23),
    borderTopRightRadius: scale(23),
    borderColor: colors.greyHomeBorder,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    // shadowColor: '#000',
    // shadowOffset: {width: 2, height: 2},
    // shadowOpacity: 0.5,
    // shadowRadius: 3,
    // elevation: 0.4,
  },
  serviceSubDataContainer: {
    marginVertical: scale(20),
    marginHorizontal: scale(10),
    flexDirection: 'row',
  },
  serviceIcon: {
    resizeMode: 'contain',
    width: scale(35),
    height: scale(35),
    marginLeft: scale(10),
  },
  cartIcon: {
    resizeMode: 'contain',
    width: scale(35),
    height: scale(35),
    marginHorizontal: scale(8),
    // marginLeft: scale(1),
  },
  leftMargin: {marginLeft: scale(10), marginBottom: scale(10)},
  barContainer: {
    height: scale(200),
    marginHorizontal: scale(10),
    marginTop: scale(10),
  },
  horizontalLine: {
    height: 1,
    // width: scale(210),
    backgroundColor: colors.greyHomeBorder,
    marginHorizontal: scale(16),
    marginTop: scale(8),
    marginBottom: scale(16),
  },
  slotText: {
    fontSize: scale(14),
    fontFamily: fonts.helveticaNeueMedium,
    color: colors.teal,
    marginHorizontal: scale(17),
  },
  safteyImage: {
    height: scale(40),
    width: scale(40),
  },
  safteyContainer: {
    height: scale(60),
    width: scale(237),
    borderWidth: scale(1),
    borderColor: colors.greyHomeBorder,
    marginRight: scale(16),
    borderRadius: scale(12),
    marginVertical: scale(16),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 1,
  },
  marginLeft: {
    marginHorizontal: scale(16),
    marginRight: scale(16),
  },
  safteyTitle: {
    fontSize: fontScale(screenHeight > 700 ? 12 : 10),
    fontFamily: fonts.helveticaNeueLight,
  },
  safteyDec: {
    // fontSize: scale(14),
    fontSize: fontScale(screenHeight > 700 ? 14 : 12),
    fontFamily: fonts.helveticaNeueMedium,
  },
  searchIcon: {
    marginTop: scale(2),
  },
  flexRowCard: {
    flexDirection: 'row',
    marginHorizontal: scale(14),
    marginVertical: scale(10),
    // alignContent: 'center',
  },
  leftText: {
    marginHorizontal: scale(8),
    marginVertical: scale(5),
  },
  marginHorizontal: {},
  indicator: {
    position: 'absolute',
    top: scale(200),
    alignSelf: 'center',
  },
});
