import {StyleSheet, Platform} from 'react-native';
import {colors, fonts} from '../../constants/styles';
import {scale, screenHeight} from '../../utils/scale';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.primaryColor,
  },
  dataContainer: {
    // backgroundColor: 'rgba(0,0,0,0.8)',
    flexDirection: 'row',
    paddingTop: scale(20),
    justifyContent: 'space-between',
  },
  item: {
    backgroundColor: '#f9c2ff',
    padding: scale(20),
    marginVertical: scale(8),
  },
  header: {
    fontSize: scale(16),
    color: '#fff',
    fontWeight: 'bold',
    marginTop: scale(5),
  },
  title: {
    fontSize: scale(16),
  },
  scrollViewContainer: {
    width: '30%',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  sectionListContainer: {
    width: '50%',
    marginLeft: scale(30),
  },
  flatListConstainer: {
    marginHorizontal: scale(5),
  },
  img: {
    width: scale(180),
    height: scale(246),
    marginTop: scale(30),
    borderRadius: scale(20),
    resizeMode: 'contain',
  },
  favImg: {
    width: scale(180),
    height: scale(246),
    marginTop: scale(30),
    borderRadius: scale(20),
    resizeMode: 'contain',
    // position: 'absolute',
    // ...StyleSheet.absoluteFillObject,
    // backgroundColor: 'rgba(0,0,0,0.1)',
  },
  titleOne: {
    fontSize: scale(16),
    // fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    padding: scale(20),
    fontFamily: fonts.avenirNextRegular,
  },
  activeStyle: {
    width: scale(5),
    backgroundColor: 'orange',
    position: 'absolute',
    bottom: scale(15),
    top: scale(15),
    right: 0,
  },
  favouriteIcon: {
    width: scale(25),
    height: scale(25),
    marginHorizontal: scale(5),
    marginLeft: scale(5),
    // marginTop: scale(5),
    resizeMode: 'contain',
  },
  expiredText: {
    color: colors.white,
    fontSize: scale(10),
    fontFamily: fonts.helveticaNeueLight,
    letterSpacing: 0.5,
  },
  expiredButtonContainer: {
    position: 'absolute',
    right: scale(20),
    top: scale(60),
    zIndex: 100,
    backgroundColor: 'rgba(0,0,0,0.5)',
    paddingHorizontal: scale(10),
    paddingVertical: scale(5),
    borderRadius: scale(5),
  },
  nameText: {
    color: colors.grayBorder,
    fontSize: scale(20),
    fontFamily: fonts.helveticaNeueRegular,
    letterSpacing: 0.5,
    marginBottom: scale(20),
  },
  offerText: {
    fontSize: scale(22),
    fontFamily: fonts.helveticaNeueRegular,
    letterSpacing: 0.5,
  },
  productImage: {
    height: scale(170),
    width: scale(90),
    position: 'absolute',
    // marginLeft: scale(Platform.OS === 'android' ? 1 : -10),
    // marginTop: scale(Platform.OS === 'android' ? 1 : -2),
    // borderTopLeftRadius: scale(20),
    // resizeMode: 'contain',
    // backgroundColor: 'red',
  },
  flexDir: {
    flexDirection: 'row',
    // backgroundColor: 'blue',
  },
  logoImage: {
    height: scale(60),
    width: scale(65),
    borderRadius: scale(6),
    // resizeMode: 'contain',
    // marginHorizontal: scale(20),
    marginTop: scale(24),
    position: 'absolute',
    right: scale(14),
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.44,
    shadowRadius: 1,
    elevation: 16,
  },
  alignProductTextWidth: {
    // marginVertical: scale(10),
    color: colors.white,
    fontSize: scale(14),
    fontFamily: fonts.helveticaNeueMedium,
    lineHeight: scale(32),
    position: 'absolute',
    bottom: scale(20),
    left: scale(16),
    // width: '20%',
  },
  alignProductTextWidth2: {
    // marginVertical: scale(10),
    color: '#827E7E',
    fontSize: scale(14),
    fontFamily: fonts.proximaNovaALight,
    lineHeight: scale(32),
    position: 'absolute',
    bottom: scale(1),
    left: scale(16),
    // width: '20%',
  },
  nameContain: {
    marginHorizontal: scale(24),
    marginTop: scale(
      screenHeight < 700 ? (Platform.OS === 'android' ? -45 : -20) : 5,
    ),
  },
  subText: {
    marginHorizontal: scale(24),
    color: colors.white,
    fontSize: scale(15),
    fontFamily: fonts.helveticaNeueLight,
    marginTop: scale(10),
  },

  productImageFav: {
    height: scale(185),
    width: scale(165),
    marginLeft: scale(Platform.OS === 'android' ? 1 : -10),
    marginTop: scale(Platform.OS === 'android' ? 0 : -6),
    borderTopLeftRadius: scale(12),
    borderTopRightRadius: scale(20),
    // resizeMode: 'contain',
    // backgroundColor: 'red',
  },
  logoImageFav: {
    height: scale(40),
    width: scale(40),
    borderRadius: scale(6),
    // resizeMode: 'contain',
    // marginHorizontal: scale(20),
    marginTop: scale(20),
    // right: scale(30),
    right: scale(Platform.OS === 'android' ? 50 : 45),
  },

  alignProductTextWidthFav: {
    marginHorizontal: scale(24),
    marginVertical: scale(20),
    color: colors.white,
    fontSize: scale(14),
    fontFamily: fonts.helveticaNeueMedium,
    // lineHeight: scale(32),
    // width: '20%',
  },
  manageNoFavContain: {},
  mainContain: {
    alignItems: 'center',
    marginHorizontal: scale(Platform.OS === 'android' ? -12 : -6),
    marginVertical: scale(-15),
  },
  gradientContain: {
    marginVertical: scale(20),
    width: Platform.OS === 'android' ? '80%' : '85%',
    borderRadius: scale(16),
  },
  mainComponent: {
    marginHorizontal: scale(14),
    borderRadius: scale(24),
    height: scale(
      screenHeight < 700 ? (Platform.OS === 'android' ? 430 : 480) : 504,
    ),
    width: scale(342),
    marginTop: screenHeight < 700 ? scale(5) : scale(30),
    //     marginTop: screenHeight > 700 ? scale(25) : scale(30),
  },
  couponShield: {
    marginHorizontal: scale(17),
    borderRadius: scale(12),
    // paddingHorizontal: scale(10),
    marginTop: scale(20),
    height: scale(104),
    width: scale(342),
    justifyContent: 'center',
  },
  couponShieldTextTitle: {
    fontSize: scale(16),
    fontFamily: fonts.helveticaNeueMedium,
    width: '70%',
    color: colors.White,
  },
  couponShieldTextTitle2: {
    fontSize: scale(13),
    fontFamily: fonts.helveticaNeueLight,
    width: '70%',
    marginVertical: scale(5),
    color: colors.White,
  },
  couponShieldTextTitle3: {
    fontSize: scale(12),
    fontFamily: fonts.helveticaNeueMedium,
    color: colors.White,
    // width: '70%',
  },
  flexRow: {
    flexDirection: 'row',
    marginVertical: scale(5),
    // marginLeft: scale(8),
    marginHorizontal: scale(20),
  },
  menuContainer: {
    flexDirection: 'row',
  },
  arrowRight: {
    marginHorizontal: scale(5),
  },
  couponShieldImage: {
    height: scale(120),
    width: scale(120),
    resizeMode: 'contain',
    position: 'absolute',
    right: scale(-20),
    top: scale(-20),
  },
  horizontalSide: {
    marginLeft: scale(16),
    marginTop: scale(32),
    // marginBottom: scale(24),
  },
  headText: {
    fontSize: scale(22),
    fontFamily: fonts.helveticaNeueCondensedBold,
  },
  productContain: {
    marginTop: scale(24),
    marginRight: scale(16),
  },
  bottom: {
    paddingBottom: scale(100),
  },
});
