// User
export const SET_OTP_STATUS = 'SET_OTP_STATUS';
export const FETCH_OTP_STATUS = 'FETCH_OTP_STATUS';
export const FETCH_VERIFY_OTP = 'FETCH_VERIFY_OTP';
export const SET_VERIFY_OTP = 'SET_VERIFY_OTP';
export const USER_EDIT = 'USER_EDIT';
export const USER_LOGOUT = 'USER_LOGOUT';
export const SET_USER_CURRENT_LOCATION = 'SET_USER_CURRENT_LOCATION';

// API RELATED
export const API = 'API';
export const API_START = 'API_START';
export const API_END = 'API_END';
export const ACCESS_DENIED = 'ACCESS_DENIED';
export const API_ERROR = 'API_ERROR';

// SwithTheme
export const SWITCH_THEME = 'SWITCH_THEME';

// AlgoliaConfig
export const FETCH_ALGOLIA_CONFIG = 'FETCH_ALGOLIA_CONFIG';

// Salon Detail
export const FETCH_SALON_DETAILS = 'FETCH_SALON_DETAILS';
export const LIST_ALL_SALON = 'LIST_ALL_SALON';

// Stylist Detail
export const FETCH_STYLIST_DETAILS = 'FETCH_STYLIST_DETAILS';
export const LIST_ALL_STYLIST = 'LIST_ALL_STYLIST';

// Available Stylist/TimeSlot
export const ADD_SERVICE_LIST = 'ADD_SERVICE_LIST';
export const AVAILABLE_STYLIST = 'AVAILABLE_STYLIST';
export const AVAILABLE_TIME_SLOT = 'AVAILABLE_TIME_SLOT';
export const SELECTED_STYLIST = 'SELECTED_STYLIST';
export const SELECTED_DATE = 'SELECTED_DATE';
export const SELECTED_TIME = 'SELECTED_TIME';
export const AVAILABLE_DATE_SLOT = 'AVAILABLE_DATE_SLOT';

// Service API
export const ADD_SERVICE_API = 'ADD_SERVICE_API';

// Cart View/Checkout
export const VIEW_CART = 'VIEW_CART';
export const CHECKOUT_API = 'CHECKOUT_API';
export const REMOVE_SERVICE_API = 'REMOVE_SERVICE_API';
export const ADD_SERVICE_UUID_MASTER = 'ADD_SERVICE_UUID_MASTER';
export const CHECK_SERVICE_TYPE = 'CHECK_SERVICE_TYPE';
export const FETCH_AVAILABLE_PAYMENT_OPTION = 'FETCH_AVAILABLE_PAYMENT_OPTION';
export const RAZOR_PAY_INIT = 'RAZOR_PAY_INIT';
export const RAZOR_PAY_VERIFY = 'RAZOR_PAY_VERIFY';

// Order Related
export const FETCH_PAST_ORDERS = 'FETCH_PAST_ORDERS';
export const FETCH_UPCOMING_ORDERS = 'FETCH_UPCOMING_ORDERS';
export const ORDER_FETCH_ERROR = 'ORDER_FETCH_ERROR';
export const FETCH_ORDER_DETAIL = 'FETCH_ORDER_DETAIL';
export const FETCH_MY_ORDER_HISTORY = 'FETCH_MY_ORDER_HISTORY';
export const FETCH_MY_ORDER_HISTORY_NEXT = 'FETCH_MY_ORDER_HISTORY_NEXT';
export const FETCH_ORDER_HISTORY_DETAIL = 'FETCH_ORDER_HISTORY_DETAIL';

// AppointMent Detail

export const FETCH_APPOINTMENT_DETAIL = 'FETCH_APPOINTMENT_DETAIL';

// Paginate Order
export const FETCH_PAST_NEXT_ORDERS = 'FETCH_PAST_NEXT_ORDERS';
export const FETCH_UPCOMING_NEXT_ORDERS = 'FETCH_UPCOMING_NEXT_ORDERS';
export const REQUEST_CANCLE_ORDER = 'REQUEST_CANCLE_ORDER';

// Deal

export const DEAL_DETAIL = 'DEAL_DETAIL';
export const FETCH_DEAL_LIST = 'FETCH_DEAL_LIST';
export const DEAL_FAVOURITE_ADD_REMOVE = 'DEAL_FAVOURITE_ADD_REMOVE';
export const LIST_DEAL_TAGS = 'LIST_DEAL_TAGS';
export const ADD_DEAL_CART = 'ADD_DEAL_CART';
export const REMOVE_DEAL_CART = 'REMOVE_DEAL_CART';
export const CHECKOUT_API_DEAL = 'CHECKOUT_API_DEAL';
export const FETCH_FAVOURITE_DEAL = 'FETCH_FAVOURITE_DEAL';
export const DEAL_ORDER_DETAIL = 'DEAL_ORDER_DETAIL';
export const FETCH_PAST_FAV_DEAL_ORDERS = 'FETCH_PAST_FAV_DEAL_ORDERS';
export const FETCH_MY_DEALS = 'FETCH_MY_DEALS';
export const FETCH_MY_DEALS_NEXT = 'FETCH_MY_DEALS_NEXT';
export const FETCH_MY_DEAL_DETAIL = 'FETCH_MY_DEAL_DETAIL';

// Schedule Cart

export const VIEW_SCHEDULE_CART = 'VIEW_SCHEDULE_CART';
export const GET_ADDABLE_SERVICE = 'GET_ADDABLE_SERVICE';
export const ADD_SCHEDULE_API = 'ADD_SCHEDULE_API';
export const REMOVE_SCHEDULE_API = 'REMOVE_SCHEDULE_API';
export const CHECKOUT_SCHEDULE_API = 'CHECKOUT_SCHEDULE_API';
export const CANCEL_SCHEDULE_API = 'CANCEL_SCHEDULE_API';
